# Generated by Django 5.2.7 on 2025-10-14 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advertisements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Ф. И. О."),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advertisements.advertisement",
                        verbose_name="Рекламная кампания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Потенциальный клиент",
                "verbose_name_plural": "Потенциальные клиенты",
            },
        ),
    ]
